### ISSUE TITLE
Show in-progress updates during the compile and upload step 

### ISSUE THREAD

**Issue by mstevetodd** [DCC-EX/EX-Installer#72] opened 2023-07-07 14:02 UTC
### Problem/idea statement

Currently, once the user presses "Load", no updates are providing until the compile and upload has completed (or failed). Then all messages are shown at once. For example, there are a number of timeout retries if the hardware does not respond, but the user is unaware of these until all have failed.

It would be ideal if the user could see a "live" output from the compiler and uploader, similar to what is shown when performing this step in pio.

### Alternatives or workarounds

none

**Comment by peteGSX** [comment] 2023-07-07 19:02
FYI this is a duplicate of https://github.com/DCC-EX/EX-Installer/issues/33, will close this one but it's linked.

**Closed by peteGSX** 2023-07-07 19:02 UTC
Labels: Enhancement, EX-Installer
